
ON_CLASS_IO(Automata<State32>)
ON_CLASS_IO(Automata<State4B>)
ON_CLASS_IO(Automata<State5B>)
ON_CLASS_IO(Automata<State6B>)
//ON_CLASS_IO(Automata<State7B>)

ON_CLASS_IO(DAWG<State32>)
ON_CLASS_IO(DAWG<State4B>)
ON_CLASS_IO(DAWG<State5B>)
ON_CLASS_IO(DAWG<State6B>)
//ON_CLASS_IO(DAWG<State7B>)

//ON_CLASS_IO(DAWG0<DAWG0_State<State32> >)
//ON_CLASS_IO(DAWG0<DAWG0_State<State4B> >)
//ON_CLASS_IO(DAWG0<DAWG0_State<State5B> >)
//ON_CLASS_IO(DAWG0<DAWG0_State<State6B> >)
//ON_CLASS_IO(DAWG0<DAWG0_State<State7B> >)

ON_CLASS_IO(LinearDFA<2>)
ON_CLASS_IO(LinearDFA<3>)
ON_CLASS_IO(LinearDFA<4>)
ON_CLASS_IO(LinearDFA<5>)
ON_CLASS_IO(LinearDFA<6>)

//ON_CLASS_IO(LinearDFA2<3>)
ON_CLASS_IO(LinearDFA2<4>)
ON_CLASS_IO(LinearDFA2<5>)
//ON_CLASS_IO(LinearDFA2<6>)

//ON_CLASS_IO(LinearDFA3<3>)
ON_CLASS_IO(LinearDFA3<4>)
ON_CLASS_IO(LinearDFA3<5>)
//ON_CLASS_IO(LinearDFA3<6>)

//ON_CLASS_IO(LinearDAWG<2>)
ON_CLASS_IO(LinearDAWG<3>)
ON_CLASS_IO(LinearDAWG<4>)
ON_CLASS_IO(LinearDAWG<5>)
ON_CLASS_IO(LinearDAWG<6>)

#undef ON_CLASS_IO
