
.PHONY: install clean

FILTER_HOME_PATH=.
#FILTER_HOME_PATH := $(shell cd $(GS_LIBRARY_RELATIVE_PATH); pwd)

VERSION=1.0.0
#TAG=test

SRV_BIN=query_filter
SRV_BIN_DEBUG=query_filter_debug

SRC=$(wildcard ./*.cpp)
OBJ=$(patsubst %.cpp,%.o,$(SRC))
OBJ_DEBUG=$(patsubst %.cpp,%_d.o,$(SRC))


GCC472_PATH=/usr/local/gcc-4.7.2
CC = env LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:$(GCC472_PATH)/lib:/usr/local/mpc/lib $(GCC472_PATH)/bin/g++
CFLAGS_COMMON = -Wall -Wno-deprecated -Wno-strict-aliasing -D_REENTRANT
CFLAGS_O = $(CFLAGS_COMMON) -g -O2
CFLAGS_D = $(CFLAGS_COMMON) -g  

INCLUDES =  -I./ \
            -I${FILTER_HOME_PATH} \
            -I${FILTER_HOME_PATH}/nlp/include \

LIBS_COMMON = -L$(FILTER_HOME_PATH)\
              -L${FILTER_HOME_PATH}/libevent/lib -lthrift -levent \
              -L${COMMON_LIB_PATH}/sign/lib -lsign \
              -L${COMMON_LIB_PATH}/log/lib -llog -llog4cpp \
              -L${COMMON_LIB_PATH}/config/lib -lconfig \
              -lrt -lpthread

LIBS_O =-L${FILTER_HOME_PATH}/nlp/lib64 -lnlpanalysis -lQueryClassify -lsentencestructure -lsynonym -lsegwords -ldictEncode  -lutility 

LIBS_D = -L${FILTER_HOME_PATH}/nlp/lib64 -lnlpanalysis -lQueryClassify -lsentencestructure -lsynonym -lsegwords -ldictEncode  -lutility 

all: $(SRV_BIN) $(SRV_BIN_DEBUG)
	@echo ""
	@echo "filter compile OK"
	@echo ""

$(SRV_BIN): $(OBJ)
	$(CC) -o $(SRV_BIN) $(OBJ) $(INCLUDES)  $(LIBS_O) $(CFLAGS_O)
	#mv $(SRV_BIN) ${LOCAL_INSTALL_PATH}

$(SRV_BIN_DEBUG): $(OBJ_DEBUG)
	$(CC) -o $(SRV_BIN_DEBUG) $(OBJ_DEBUG) $(INCLUDES) $(LIBS_D) $(CFLAGS_D)
	#mv $(SRV_BIN_DEBUG) ${LOCAL_INSTALL_PATH}

$(OBJ): %.o: %.cpp
	$(CC) -c $< -o $@ $(INCLUDES) $(CFLAGS_O)

$(OBJ_DEBUG): %_d.o: %.cpp
	$(CC) -c $< -o $@ $(INCLUDES) $(CFLAGS_D)


clean:
	@rm -f $(SRV_BIN)
	@rm -f $(SRV_BIN_DEBUG)
	@rm -f *.o
